[build]
  base    = "frontend"          
  command = "pnpm run build"    
  publish = "dist"              

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "9.0.0"
  NETLIFY_USE_PNPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
